### ISSUE TITLE
Create Markdown Template for Pull Requests (PR)

### ISSUE THREAD

**Issue by MosesSupposes** [derekmeegan/folio-graph#15]
## Description:
We need a standardized markdown template for contributors to use when creating pull requests. This will ensure that all necessary information is provided, making it easier to review and merge changes. The template should include sections for the purpose of the PR, changes made, and any related issues or dependencies.

## Task List:

Create a markdown file named PULL_REQUEST_TEMPLATE.md in the .github directory.
Include the following sections in the template:
- Description
- Related Issue
- Proposed Changes
- Checklist
- Screenshots (if applicable)

### Proposed Template Content:

```markdown
---
name: Pull Request
about: Use this template to create a pull request.
title: "[PR] - <Brief Description>"
labels: pull request
assignees: ''

---

## Description
Provide a brief description of the changes made in this PR.

## Related Issue
Link to any related issues or tickets.

## Proposed Changes
- **Change 1:** 
- **Change 2:**
- **Change 3:**

## Checklist
- [ ] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have checked my code and corrected any misspellings.
- [ ] 
## Screenshots (if applicable)
Include screenshots of any visual changes.

## Additional Context
Add any other context or information about the pull request here.
```

## Acceptance Criteria:
The `PULL_REQUEST_TEMPLATE.md` file is created in the `.github` directory.
The template includes all necessary sections and fields.
The template is reviewed and approved by a project maintainer.

## Additional Context:
This template will help maintain consistency and thoroughness in pull requests, making it easier to review and integrate changes into the project.
